### ISSUE TITLE
Column number varies in TSV output

### ISSUE THREAD

**Issue by brwnj** [tseemann/prokka#250]
Where any row is missing an entry, an EC, a gene name, or product, a tab is not inserted leaving varying row lengths in the table.

**Comment by tseemann** [comment]
@brwnj you are right, it is a bug. it's an experimental new output file and I managed to get it wrong already.

**Comment by tseemann** [comment]
Fixed - thank you @brwnj .  it was quite a subtle Perl-ism I didn't fully appreciate.

**Comment by ganiatgithub** [comment]
Hello,

I'm using prokka 1.13, but the same error still presents.

My script:
source activate /30days/uqgni1/tools/Miniconda3/envs/prokka-1.1.3
for i in /path_to_input/*.fa;do
prokka \
--outdir /path_to_output/${i##*/}_archaea.prokka \
--prefix ${i##*/} \
--cpus 8 \
--usegenus \
--kingdom Archaea \
--metagenome \
/path_to_input/${i##*/} 
done
conda deactivate

Prokka log:
[16:08:59] This is prokka 1.13.3
[16:08:59] Written by Torsten Seemann <torsten.seemann@gmail.com>
[16:08:59] Homepage is https://github.com/tseemann/prokka
[16:08:59] Local time is Mon Jun 10 16:08:59 2019
[16:08:59] You are uqgni1
[16:08:59] Operating system is linux
[16:08:59] You have BioPerl 1.007002
[16:08:59] System has 24 cores.
[16:08:59] Will use maximum of 8 cores.
[16:08:59] Annotating as >>> Archaea <<<
....
[16:09:53] Annotation finished successfully.
[16:09:53] Walltime used: 0.90 minutes
[16:09:53] If you use this result please cite the Prokka paper:
[16:09:53] Seemann T (2014) Prokka: rapid prokaryotic genome annotation. Bioinformatics. 30(14):2068-9.
[16:09:53] Type 'prokka --citation' for more details.
[16:09:53] Thank you, come again.
(END)

a few line from the .tsv output:

KEGIPPEK_00001	CDS	1080	arnB_1	2.6.1.87		UDP-4-amino-4-deoxy-L-arabinose--oxoglutarate aminotransferase
KEGIPPEK_00002	CDS	1008				hypothetical protein
KEGIPPEK_00003	CDS	1881				hypothetical protein
KEGIPPEK_00004	CDS	447				hypothetical protein
KEGIPPEK_00005	CDS	987	gmd_1	4.2.1.47		GDP-mannose 4,6-dehydratase
KEGIPPEK_00006	CDS	1062	glmU_1		COG1208	Bifunctional protein GlmU
KEGIPPEK_00007	CDS	1044				hypothetical protein
KEGIPPEK_00008	CDS	1053				hypothetical protein
KEGIPPEK_00009	CDS	1263				hypothetical protein
KEGIPPEK_00010	CDS	840				hypothetical protein
KEGIPPEK_00011	CDS	942	gmd_2	4.2.1.47		GDP-mannose 4,6-dehydratase
KEGIPPEK_00012	CDS	1170				hypothetical protein
KEGIPPEK_00013	CDS	1020	fcl_1	1.1.1.271		GDP-L-fucose synthase
KEGIPPEK_00014	CDS	1272	arnB_2	2.6.1.87		UDP-4-amino-4-deoxy-L-arabinose--oxoglutarate aminotransferase
KEGIPPEK_00015	CDS	936	fcl_2	1.1.1.271		GDP-L-fucose synthase
KEGIPPEK_00016	CDS	924	arnC_1	2.4.2.53		Undecaprenyl-phosphate 4-deoxy-4-formamido-L-arabinose transferase
KEGIPPEK_00017	CDS	2775				hypothetical protein
KEGIPPEK_00018	CDS	918	hldD_1	5.1.3.20		ADP-L-glycero-D-manno-heptose-6-epimerase
KEGIPPEK_00019	CDS	999				hypothetical protein

Any tips on how to fit it? Much appreciated!
